yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [

    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreatModel

User = get_user_model()


class Group(models.Model):
    """Создание таблицы Group"""

    title = models.CharField(
        max_length=200,
        verbose_name='Название группы'
    )
    slug = models.SlugField(unique=True)
    description = models.TextField(
        verbose_name='Описание группы'
    )

    def __str__(self):
        return self.title


class Post(CreatModel, models.Model):
    """Создание таблицы Post"""
    text = models.TextField(
        verbose_name='текст',
        help_text='Заполните это поле'
    )
    # pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts')
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='post',
        verbose_name='Выберите группу',
        help_text='Не обязательное поле')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(CreatModel, models.Model):
    """Модель комментрариев"""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Выберите пост'

    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Выберите автора'

    )

    text = models.TextField(
        'Текст комментария',
        help_text='Напишите комментарий'
    )

    # created=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='follower'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', ]

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Group, Post, User, Comment, Follow
from django.core.paginator import Paginator
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from yatube.settings import NUM_PAGE_PAGINATOR


def paginator(request, posts):
    paginator = Paginator(posts, NUM_PAGE_PAGINATOR)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    posts = Post.objects.select_related('group')
    context = {
        'page_obj': paginator(request, posts)
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.post.all()
    context = {
        'page_obj': paginator(request, posts),
        'group': group
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()

    following = Follow.objects.filter(author=author).exists()
    context = {'author': author,
               'page_obj': paginator(request, posts),
               'posts': posts,
               'following': following
               }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comment = Comment.objects.filter(post=post)
    context = {
        'posts': post,
        'form': form,
        'comments': comment
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)

    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    is_edit = True
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )

    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', post_id=post.id)

    context = {
        'form': form,
        'is_edit': is_edit
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


# posts/views.py

@login_required
def follow_index(request):
    posts = Post.objects.select_related(
        'group'
    ).filter(author__following__user=request.user)

    context = {
        'posts': posts,
        'page_obj': paginator(request, posts),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    # Дизлайк, отписка
    Follow.objects.filter(author=author, user=request.user).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
{% if is_edit %}
Редактировать запись
{% else %}
Новый пост
{% endif %}
{% endblock %}



{% block content %}

<main>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                            {% if is_edit %}
                        Редактировать запись
                            {% else %}
                           Добавить запись
                            {% endif %}

                    </div>
                    <div class="card-body">
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="form-group row my-3 p-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                    <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field }}
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                    {{ field.help_text|safe }}
                                </small>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">
                                    {% if is_edit %}
                                    Сохранить
                                    {% else %}
                                    Добавить
                                    {% endif %}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block content %}

{% include 'posts/includes/switcher.html' %}

<div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    <article>
        {% load cache %}
        {% cache 20 index_page %}
        {% load user_filters %}
        {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.created|date:"d E Y" }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text|uglify }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
        {% if post.group %}
        <br>
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}

    </article>
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
    {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}

<div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
        {{ group.description }}
    </p>
    <article>
        {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.created|date:"d E Y" }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text }}
        </p>
    </article>
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
        {% include 'includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block content %}

{% include 'posts/includes/switcher.html' %}

<div class="container py-5">
    <h1>Последние обновления на сайте</h1>

    <article>
        {% load cache %}
        {% cache 20 index_page %}
        {% load user_filters %}
        {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.created|date:"d E Y" }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text|uglify }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
        {% if post.group %}
        <br>
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}

    </article>
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
    {% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}Пост {{ posts.text|truncatewords:30 }}{% endblock %}

{% block content %}


    <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ posts.created|date:"d E Y" }}
                </li>
                {% if posts.group %}
                <li class="list-group-item">
                    Группа: {{ posts.group }}
                    <a href="{% url 'posts:group_list' posts.group.slug %}">
                        все записи группы
                    </a>
                </li>
                {% endif %}
                <li class="list-group-item">
                    Автор: {{ posts.author.username }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора:  <span>{{ posts.author.posts.count }}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' posts.author %}">
                        все посты пользователя
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% thumbnail posts.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
                {{ posts.text }}
            </p>
           {% if posts.author == request.user %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' posts.pk %}">
                редактировать запись
            </a>
            {% endif %}
            {% if user.is_authenticated %}
            <div class="card my-4">
                <h5 class="card-header">Добавить комментарий:</h5>
                <div class="card-body">
                    <form method="post" action="{% url 'posts:add_comment' posts.id %}">
                        {% csrf_token %}
                        <div class="form-group mb-2">
                            {{ form.text|addclass:"form-control" }}
                        </div>
                        <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                </div>
            </div>
            {% endif %}

            {% for comment in comments %}
            <div class="media mb-4">
                <div class="media-body">
                    <h5 class="mt-0">
                        <a href="{% url 'posts:profile' comment.author.username %}">
                            {{ comment.author.username }}
                        </a>
                    </h5>
                    <p>
                        {{ comment.text }}
                    </p>
                </div>
            </div>
            {% endfor %}
        </article>
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Профайл пользователя {{ author.first_name }} {{ author.last_name }}{% endblock %}
{% block content %}
<div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ posts.count }}</h3>
    {% if following %}
    <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
        Отписаться
    </a>
    {% else %}
    <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
        Подписаться
    </a>
    {% endif %}
</div>
<article>
    <ul>
        <li>
            Автор: {{ author.first_name }} {{ author.last_name }}
            <a href="{% url 'posts:profile' author %}">все посты пользователя</a>
        </li>

        {% for post in page_obj %}
        <li>
            Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
        {{ post.text|truncatewords:30 }}

    </p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    <br>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
</article>


{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}

{% include 'includes/paginator.html' %}
{% endblock %}